version: "3.8"
services:
  mongo_db:
    image: mongo:latest
    container_name: database
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
    restart: always
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: mongodb://mongo_db:27017/daos
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}