name: ci
on: [push, pull_request]
jobs:
  run-docker-compose:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run docker compose
        run: docker-compose up -p